server:
  port:
    8888
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG